# Site settings
title: RSE'25
description: The 2025 Robotics Software Engineering (RSE25) meeting will be held in the University of Southern Denmark, Denmark from September 8th to September 11th 2025.

url: http://rsemeeting.github.io/
baseurl: '/rse2025'

conference_title: "Robotics Software Engineering"
conference_title_short: "RSE"
year: "2025"
venue: University of Southern Denmark, Denmark
copyright: Conference Organizers
dates:
  meeting: September 9th - 11th 2025
  application:
    deadline: March 31st 2025
    extension: May 4th 2025
  notification: May 20th
  registration:
    deadline: September 9th
    # extension: 

# Color settings
color:
  primary-dark: '#9d2246'
  title: '#ebf0f4'
  links: '#0068b4'
  accent: '#d50c2f'

# conference data
background-image: /assets/SDUFacade1.jpg
directions-link: https://www.sdu.dk/en/om-sdu/sdu-campusser/odense
map-embed: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4622.110226188615!2d10.429211171358444!3d55.368255940538376!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x464d204fe2633dd5%3A0xa9604398da5c3e8a!2sUniversity%20of%20Southern%20Denmark!5e1!3m2!1sen!2sdk!4v1740484903562!5m2!1sen!2sdk
organizer-email : rsemeeting@gmail.com
application-page : https://forms.office.com/e/YT6MWPUxgr
registration-page: https://www.conferencemanager.dk/rse2025

collections:
  # - invited_speakers
  - organizers
  - sessions
  # - papers
  # - advisors

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compact # possible values: nested expanded compact compressed